### ISSUE TITLE
Does this custom firmware support adjusting RGB lighting in VIA?

### ISSUE THREAD

**Issue by kungpaogao** [chent7/fancyalice66#1]
Using the pre-flashed firmware, I'm not able to configure lighting using VIA. Does using this firmware allow me to do that?

**Comment by chent7** [comment]
It does not, and honestly not a lot of boards I see support that. Mainly, the documentation on supporting it is lacking. I will look into it, if it is some simple changes to the json file, I might support it.

**Comment by kungpaogao** [comment]
Got it, thanks for the reply! Just got this board and the company that I got it from is sending me another PCB because one of the hotswap sockets popped out, so I might try some experimentation when that comes.

Also, how does the eager debounce stuff affect the normal typing experience? If I make modifications on top of your existing firmware, should I remove it if I just want to use the keyboard "normally"?

**Comment by chent7** [comment]
Eager debounce is not noise resistant, meaning in some cases you may experience double taps. However, in real use I have never gotten double taps since switches are so good and precise now. People in the rhythm gaming community uses it due to its lower latency ([here's an interesting read](https://michael.stapelberg.ch/posts/2021-05-08-keyboard-input-latency-qmk-kinesis/#eagerdebounce)).

For making changes yourself, you need to setup QMK on your machine (much easier on a linux environment, use wsl or virtual machine). Then you can remove the line setting the debounce algorithm in rules.mk and compile a new firmware. QMK has undergone some changes and I haven't updated the code (especially regarding rotatry encoder functions), so you may get errors. Best bet would be to use my fork of QMK. If you don't know how to get started please read through QMK Docs.

**Comment by chent7** [comment]
Anyway basically you can use the keyboard normal with eager debounce, you won't notice anything different and might even perform better in games.

**Comment by kungpaogao** [comment]
awesome, thanks for the in-depth response! I'll close this issue for now and let you know if there are any updates
